export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SUBJECTS_FETCHED = "SUBJECTS_FETCHED";
export const SUBJECT_CREATED = "SUBJECT_CREATED";
export const SUBJECT_FETCHED = "SUBJECT_FETCHED";
export const SUBJECT_DELETED = "SUBJECT_DELETED";

export const SUBJECT_DATA_FETCHED = "SUBJECT_DATA_FETCHED";
export const SUBJECT_DATA_CREATED = "SUBJECT_DATA_CREATED";
export const SUBJECT_DATA_EDITED = "SUBJECT_DATA_EDITED";
export const SUBJECT_DATA_DELETED = "SUBJECT_DATA_DELETED";

export const SEARCH_RESULTS = "SEARCH_RESULTS";
